# nothing here
CONFIG_MULTITHREADING=n

CONFIG_GPIO=n

CONFIG_NRFX_SPIM21=y
CONFIG_NRFX_SPIS21=y
CONFIG_NRFX_TWIM21=y
CONFIG_NRFX_TWIS21=y
CONFIG_NRFX_UARTE21=y

CONFIG_NRFX_SPIM22=y
CONFIG_NRFX_SPIS22=y
CONFIG_NRFX_TWIM22=y
CONFIG_NRFX_TWIS22=y
CONFIG_NRFX_UARTE22=y

CONFIG_NRFX_SPIM30=y
CONFIG_NRFX_SPIS30=y
CONFIG_NRFX_TWIM30=y
CONFIG_NRFX_TWIS30=y
CONFIG_NRFX_UARTE30=y

CONFIG_NRFX_GPIOTE20=y
CONFIG_NRFX_GPIOTE30=y

CONFIG_NRFX_I2S20=y

CONFIG_NRFX_COMP=y

CONFIG_NRFX_PWM20=y
CONFIG_NRFX_PWM21=y
CONFIG_NRFX_PWM22=y
